/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mcmaster01.core;
import org.bukkit.plugin.java.JavaPlugin;
import org.mcmaster01.listeners.PlayerFlightListener;
import org.mcmaster01.listeners.PlayerGrabListener;
import org.mcmaster01.listeners.PlayerInteractAtEntityListener;
import org.mcmaster01.listeners.PlayerInteractListener;
import org.mcmaster01.listeners.PlayerJoinListener;
import org.mcmaster01.listeners.PlayerMoveListener;
import org.mcmaster01.listeners.PlayerSmashListener;
import org.mcmaster01.listeners.PlayerThrowListener;
import org.mcmaster01.listeners.PlayerToggleSneakListener;
/**
 * Main class that will be used for registering all events for SmashBros plugin :)
 */
public class SmashBrosPlugin extends JavaPlugin {

@Override
public void onEnable() {
    getServer().getPluginManager().registerEvents(new PlayerJoinListener(), this);
    getServer().getPluginManager().registerEvents(new PlayerMoveListener(), this);
    getServer().getPluginManager().registerEvents(new PlayerFlightListener(), this);
    getServer().getPluginManager().registerEvents(new PlayerSmashListener(), this);
    getServer().getPluginManager().registerEvents(new PlayerToggleSneakListener(), this);
    getServer().getPluginManager().registerEvents(new PlayerInteractAtEntityListener(), this);
    getServer().getPluginManager().registerEvents(new PlayerGrabListener(), this);
    getServer().getPluginManager().registerEvents(new PlayerInteractListener(), this);
    getServer().getPluginManager().registerEvents(new PlayerThrowListener(), this);



} 
  

}
