/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.gradleup.shadow") version "9.4.2"
}

java {
  toolchain.languageVersion.set(JavaLanguageVersion.of(26))
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
    name = "papermc"
    url = uri("https://repo.papermc.io/repository/maven-public/")
  }
}




dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    compileOnly("io.papermc.paper:paper-api:26.1.2.build.+")
    
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
